spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flight_app
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      registerWithEureka: true
      fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost