spring:
  datasource:
    url: jdbc:mysql://${HOST_DB}:${PORT_DB}/flight_app
    username: ${USER_DB}
    password: ${PASS_DB}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST_EUREKA}:8761/eureka
      registerWithEureka: true
      fetch-registry: true
  instance:
    hostname: ${IP_HOST}
    non-secure-port: ${PORT_HOST}
#    prefer-ip-address: true
