spring:
  application:
    name: product-service
server:
  port: 9000

eureka:
  instance:
    instance-id: B_instance
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true